<Project Sdk="Microsoft.NET.Sdk">

<ItemGroup>
  <EmbeddedResource Include="Resources\two-arrows-up1.png" />
  <EmbeddedResource Include="Resources\two-arrows-up2.png" />
</ItemGroup>

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>x64</PlatformTarget>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <!-- Core MelonLoader -->
    <Reference Include="MelonLoader" HintPath="MelonLoader_Libs/MelonLoader.dll" />
    <Reference Include="0Harmony" HintPath="MelonLoader_Libs/0Harmony.dll" />
    
    <!-- Game Assembly -->
    <Reference Include="Assembly-CSharp" HintPath="MelonLoader_Libs/Assembly-CSharp.dll" />
    
    <!-- Il2Cpp Runtime -->
    <Reference Include="Il2CppInterop.Runtime" HintPath="MelonLoader_Libs/Il2CppInterop.Runtime.dll" />
    
    <!-- Unity Engine -->
    <Reference Include="UnityEngine.CoreModule" HintPath="MelonLoader_Libs/UnityEngine.CoreModule.dll" />
    <Reference Include="Unity.Addressables" HintPath="MelonLoader_Libs/Unity.Addressables.dll" />
    
    <!-- Il2Cpp mscorlib -->
    <Reference Include="Il2Cppmscorlib" HintPath="MelonLoader_Libs/Il2Cppmscorlib.dll" />
  </ItemGroup>

</Project>